apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: xsuaa
spec:
  clusterServiceClassExternalName: xsuaa
  clusterServicePlanExternalName: application
  parameters:
    xsappname: btptour
    tenant-mode: dedicated
    scopes:
      - name: "$XSAPPNAME.PERSONS"
        description: "Zorro People app access"
    role-templates:
      - name: BTPTour
        description: BTP Tour User
        scope-references:
          - "$XSAPPNAME.PERSONS"


