apiVersion: v1
kind: ServiceAccount
metadata:
  name: btptour-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: btptour-role
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
      - gateway.kyma-project.io
      - servicecatalog.k8s.io
    resources:
      - deployments
      - replicasets
      - pods
      - jobs
      - configmaps
      - apirules
      - serviceinstances
      - servicebindings
      - serviceaccounts
      - services
      - secrets
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: btptour-role-binding
subjects:
  - kind: ServiceAccount
    name: btptour-service-account
roleRef:
  kind: Role
  name: btptour-role
  apiGroup: rbac.authorization.k8s.io
