site_name: BTP Tour
docs_dir: docs
site_dir: docs-gen
repo_url: hhttps://github.com/sebbae/btptour
site_url: https://github.com/pages/sebbae/btptour
nav:
    - 'Home': 'index.md'
    - 'Getting Started':
        - 'Business Application Studio': 'content/config/bas.md'
        - 'Kubernetes/Kyma': 'content/config/kyma.md'
theme:
    name: null
    custom_dir: 'docs/theme/material'
    logo: 'assets/btptour_logo.png'
    icon:
      logo: 'btptour'
      repo: 'github'
    favicon: 'assets/favicon.ico'
    language: 'en'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    feature:
        tabs: true
    palette:
        scheme: 'btptour'
extra_css:
    - 'theme/stylesheets/extra.css'
markdown_extensions:
    - admonition             # block-styled content like "!!! note"
    - footnotes              # footnotes; references with [^1] inline and decl's with [^1]: Lorem ipsum, ...
    - fenced_code
    - attr_list              # link attributes like e.g. target=_blank
